---
# Só mude aqui!!!!
author: "Sarah Oliveira Ramalho"
title: "Tabulação do motor de vedação challenger"
bibliography: referencias.bib
# A partir daqui nao faca alteracoes!!!!!
link-citations: true
csl: associacao-brasileira-de-normas-tecnicas-ipea.csl
subtitle: "<a href='https://bendeivide.github.io/courses/epaec/' target='_blank'>Estatística e Probabilidade</a> </br> <a href='https://bendeivide.github.io' target='_blank'>Prof. Ben Dêivide (DEFIM/CAP/UFSJ)</a>"
include-before-body: header.html
date: now
date-format: "31/03/2026, HH:mm"
lang: pt-BR
format:
  html:
    toc: true
    number-sections: true
    theme: bootstrap
    #css: styles.css
    code-fold: true
    code-tools: true
execute:
  echo: true
  warning: false
  message: false
---


## 📌 Introdução

Em 28 de janeiro de 1986, o ônibus espacial Space Shuttle Challenger foi lançado 
pela NASA a partir do Kennedy Space Center.A missão durou apenas 73 segundos.Du
rante a subida, ocorreu uma falha catastrófica que levou à explosão da nave,re
sultando na morte de 7 astronautas.Diante disso, Foram realizados diversos estu
dos pela NASA para identificar as causas da falha. A primeira atenção se voltou 
para a temperatura (ºF) do anel de vedação :

dados <- c(84,49,61,40,83,67,45,66,70,69,80,58,
           68,60,67,72,73,70,57,63,70,78,52,67,
           53,67,75,61,70,81,76,79,75,76,58,31)


## 🎯 Objetivos

Fazer os cálculos estatísticos :
1)Média      3)Moda                5) lim inferior   7)Número de classes
2)Mediana    4)lim superior        6) Amplitude      8)Desvio padrão

### Objetivo geral

Conhecer o efeito prático de cálculos estatísticos; tabular.

### Objetivos específicos

- Aplicar estatística descritiva  
- Construir gráficos  
- Interpretar resultados  

---

## 📚  Fundamentação Teórica

Apresente os conceitos principais:

- Média
- Variância
- Desvio padrão
- Amostragem
- Lim inferior
-Lim 
---

## ⚙️ Metodologia

Peguei os dados do capítulo 2, exemplo 2.1 do livro Estatística & Probabilidade
aplicada às Engenharias e Ciências e baseado nisso, farei os cálculos e tabula
ção.
---

## 🔍 Resultados e Discussão


Procure não apenas descrever, mas **interpretar os dados**.

### 💬 Exemplo de como citar uma referência bibliográfica

Depois de inserido as informaçõe no arquivo **referencias.bib**, use:

- Segundo @Rbasico2022
- Tudo é um objeto em R [@Rbasico2022]


## 🧠 Considerações finais



Evite repetir apenas os resultados; foque nas **conclusões e reflexões** sobre a prática realizada.

## Aprenda Quarto

Acesse [Quarto](https://quarto.org/).

## 📖 Referências